### ISSUE TITLE
About update interval for Runtime compatibility website

### ISSUE THREAD

**Issue by nabetti1720** [unjs/runtime-compat#123]
Hello to all contributors.

First of all, thank you for publishing this [Runtime compatibility website](https://runtime-compat.unjs.io/) where we can get great insight.

I am currently working with the [LLRT](https://github.com/awslabs/llrt) project in a small way as a contributor.
LLRT just released [v0.1.13-beta](https://github.com/awslabs/llrt/releases/tag/v0.1.13-beta) last week.

There have been some improvements in terms of WinterCG compliance, and we thought we could measure the degree of improvement on this website, but it appears that information on the new version has not yet been updated.

What is the update interval for this website?

I apologize if you are experiencing problems with the update procedure and have already identified this as an issue.

**Comment by ascorbic** [comment]
It's updated whenever we merge one of the update PRs 😁 
I just did that, which updates LLRT to 0.1.13-beta. In general, if you look at the latest "update runtime compat data" PR you should see the latest version

**Comment by nabetti1720** [comment]
Hi @ascorbic . Thank you very much for your quick response!
We have seen that the website has been updated here as well.

PRs are generated automatically, but human judgment comes into play as to whether to merge them or not?

Additionally, how do I request to have the latest data merged in the future?
Should I make a mentions in the comments section of the PR that is automatically generated?

**Comment by ascorbic** [comment]
Honestly we should probably just auto-merge them. But yes, if there's been an update then check the PR, see if it shows up in the deploy preview, and if it is then just add a comment.

**Comment by nabetti1720** [comment]
Thank you very much. This issue has already served its purpose and will be closed.
