### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by linusg** [unjs/runtime-compat#56]
The first link on `https://runtime-compat.unjs.io` points to `https://github.com/unjs/runtime-compat-data`, which 404s. This should either link to `https://github.com/unjs/runtime-compat` (this repo) or `https://github.com/unjs/runtime-compat/tree/main/packages/runtime-compat-data` (the applicable subdir).

**Comment by pi0** [comment]
PR welcome to update link 🙏🏼
