### ISSUE TITLE
`BroadcastChannel` is displayed at not supported for Deno, but should be supported

### ISSUE THREAD

**Issue by QuiiBz** [unjs/runtime-compat#87]
### Describe the feature

`BroadcastChannel` does exist in Deno: https://deno.land/api@v1.41.3?s=BroadcastChannel
But the test seems to fail and reports that it's not supported: https://runtime-compat.unjs.io/#BroadcastChannel

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ascorbic** [comment]
It doesn't seem to be defined on `globalThis`

**Comment by nicolo-ribaudo** [comment]
Support in Deno is still experimental and behind the `--unstable` CLI flag

**Comment by ascorbic** [comment]
I'm going to close this because we're not showing features that are not enabled by default.

**Comment by QuiiBz** [comment]
Thanks for the precision, closing for now.
