### ISSUE TITLE
Async localstorage 

### ISSUE THREAD

**Issue by wmertens** [unjs/runtime-compat#97]
### Describe the feature

Missing: https://nodejs.org/api/async_context.html#class-asynclocalstorage

Supported by node, bun, deno, cloudflare workers at least.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ascorbic** [comment]
We're only including web platform APIs right now, not Node APIs. We do have an issue for also tracking Node compatibility, and if we implement that then that's where we'd put ALS. AsyncContext would make sense in here once it gets through TC39.

**Comment by wmertens** [comment]
Makes sense, closing for now then
